// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAleTpOEYkY3GBIu3FOfmpDyVun5ALBWok',
    appId: '1:521423723495:web:c02a285cefdb5e86cd7b42',
    messagingSenderId: '521423723495',
    projectId: 'recipe-app-e1552',
    authDomain: 'recipe-app-e1552.firebaseapp.com',
    storageBucket: 'recipe-app-e1552.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9WdJ5wZSqFy2oUHte7mAeAP-_wrTtqLE',
    appId: '1:521423723495:android:2fd47b402970376bcd7b42',
    messagingSenderId: '521423723495',
    projectId: 'recipe-app-e1552',
    storageBucket: 'recipe-app-e1552.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCsm8StgA-mLPaFH_xAQNpHEhf1W6NZZM',
    appId: '1:521423723495:ios:20a5a982614c82e4cd7b42',
    messagingSenderId: '521423723495',
    projectId: 'recipe-app-e1552',
    storageBucket: 'recipe-app-e1552.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCsm8StgA-mLPaFH_xAQNpHEhf1W6NZZM',
    appId: '1:521423723495:ios:20a5a982614c82e4cd7b42',
    messagingSenderId: '521423723495',
    projectId: 'recipe-app-e1552',
    storageBucket: 'recipe-app-e1552.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAleTpOEYkY3GBIu3FOfmpDyVun5ALBWok',
    appId: '1:521423723495:web:fc98ad4a35a0084bcd7b42',
    messagingSenderId: '521423723495',
    projectId: 'recipe-app-e1552',
    authDomain: 'recipe-app-e1552.firebaseapp.com',
    storageBucket: 'recipe-app-e1552.firebasestorage.app',
  );
}
